- name: add visudo with NOPASS
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo    ALL=(ALL:ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: "user:{{ansible_ssh_user}} add sudo group"
  user:
    name: "{{ansible_ssh_user}}"
    groups: sudo
    append: yes
