- name: update all package
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: upgrade all package
  apt:
    upgrade: yes

- name: install basic packages
  apt:
    name:
      - sudo
      - chrony
      - nfs-common
      - tcpdump
      - sysstat
      - lsof
      - traceroute
      - fio
      - wget
      - curl
      - vim
      - parted
      - rsync
    state: latest

