# https://docs.docker.com/engine/install/ubuntu/
- name: remove pre-installed docker
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent

- name: setup the repository
  block:
    - name: update the apt package index and install packages to allow apt to use a repository over HTTPS
      block:
        - name: update the packages
          apt:
            name: "*"
            state: latest
            update_cache: yes

        - name: install packages
          apt:
            name:
              - ca-certificates
              - curl
              - gnupg
            state: latest

    - name: add Docker’s official GPG key
      block:
        - name: make keyrings directory
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: 0755

        - name: check GPG key existence
          stat:
            path: /etc/apt/keyrings/docker.gpg
          register: gpg_existence

        - name: verify GPG key
          shell:
            cmd: gpg --dry-run -q --import --import-options import-show /etc/apt/keyrings/docker.gpg
          register: gpg_fingerprint
          failed_when: gpg_fingerprint.rc != 2
          when: gpg_existence.stat.exists

        - name: install GPG key
          shell:
            cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          when: not gpg_existence.stat.exists

        - name: chmod docker.gpg
          file:
            path: /etc/apt/keyrings/docker.gpg
            mode: a+r

    - name: set up the repository
      apt_repository:
        repo: "deb [arch={{cpu_arch}} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
        filename: docker
        state: present

- name: install Docker engine
  block:
    - name: update the apt package index
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: install Docker engine, containerd and Docker compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

- name: install Docker for ansible(python)
  block:
    - name: install python3
      apt:
        name:
          - python3
          - python3-pip
        state: latest

    - name: install pip packages
      pip:
        name:
          - docker
          - docker-compose

- name: enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes

#- name: verify that the Docker Engine installation is successful by running the hello-world image

- name: add user to docker group
  user:
    name: "{{ansible_ssh_user}}"
    groups: docker
    append: yes
  notify:
    - restart docker
