- name: install base packages
  include_tasks: install-base-packages.yml

- name: set sudoer
  include_tasks: set-sudo.yml

- name: install docker
  include_tasks: install-docker.yml

- name: reboot os
  include_tasks: reboot.yml
  when: reboot is defined and reboot | bool
